
services:
  web:
    build: .
    command: gunicorn app.todo_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=todo_backend.settings
      - PYTHONPATH=/code/app
      - CELERY_BROKER_URL=redis://redis:6379/0  # <--- BROKER PARA CELERY


  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A app.todo_backend worker --loglevel=info
    volumes:
      - .:/code
    working_dir: /code
    depends_on:
      - redis
      - web
    environment:
      - DJANGO_SETTINGS_MODULE=todo_backend.settings
      - PYTHONPATH=/code/app
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data:
